name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag cargo-planner-image:latest
          docker run --rm -p 5000:80 --name cargo-dev cargo-planner-image

  deploy:
    runs-on: self-hosted

    steps:
      - run: docker images
